#Set it to 0 to make the ban permanent.
#Set it to any positive number to choose how many days the ban lasts for.
#Set it to any negative number to make the plugin use a custom command instead of banning players.
banTime: 0

#This is optional.
#Type <P> to use the player's name.
command: "ban <P>"

#Set it to false if you'd like your players to not use elytras
elytra-toggle: true

#60 hp = 30 hearts
maxHealth: 60.0

#1 health point is half a heart
defaultHealth: 20.0

#The amount of hearts that are stolen or lost
stolenHealth: 2.0

#Whether a player loses health if they are not killed by a player
loseLifeIfNotKilledByPlayer: false

HeartRecipe:
  Slot0: "DIAMOND_BLOCK"
  Slot1: "OBSIDIAN"
  Slot2: "DIAMOND_BLOCK"
  Slot3: "GOLD_BLOCK"
  Slot4: "NETHERITE_INGOT"
  Slot5: "GOLD_BLOCK"
  Slot6: "DIAMOND_BLOCK"
  Slot7: "OBSIDIAN"
  Slot8: "DIAMOND_BLOCK"
